
[ClassVersion("1.0.0.0"), FriendlyName("xRDRemoteApp")]
class MSFT_xRDRemoteApp : OMI_BaseResource
{
    [key, Description("Specifies an alias for the RemoteApp program.")] string Alias;
    [key, Description("Specifies the name of the personal virtual desktop collection or session collection. The cmdlet publishes the RemoteApp program to this collection. ")] string CollectionName;
    [key, Description("Specifies a name to display to users for the RemoteApp program.")] string DisplayName;
    [key, Description("Specifies a path for the executable file for the application. Do not include any environment variables.")] string FilePath;
    [write, Description("Specifies a path for the application executable file. This path resolves to the same location as the value of the FilePath parameter, but it can include environment variables. ")] string FileVirtualPath;
    [write, Description("Specifies the name of the folder that the RemoteApp program appears in on the Remote Desktop Web Access (RD Web Access) webpage and in the Start menu for subscribed RemoteApp and Desktop Connections. ")] string FolderName;
    [write, Description("Specifies whether the RemoteApp program accepts command-line arguments from the client at connection time. The acceptable values for this parameter are:  Allow, DoNotAllow, Require")] string CommandLineSetting;
    [write, Description("Specifies a string that contains command-line arguments that the client can use at connection time with the RemoteApp program. ")] string RequiredCommandLine;
    [write, Description("Specifies the index within the icon file (specified by the IconPath parameter) where the RemoteApp program’s icon can be found.")] uint32 IconIndex;
    [write, Description("Specifies the path to a file containing the icon to display for the RemoteApp program identified by the Alias parameter.")] string IconPath;
    [write, Description("Specifies a domain group that can view the RemoteApp in RD Web Access, and in RemoteApp and Desktop Connections. To allow all users to see a RemoteApp program, provide a value of Null.")] string UserGroups;
    [write, Description("Specifies whether to show the RemoteApp program in the RD Web Access server, and in RemoteApp and Desktop Connections that the user subscribes to. ")] boolean ShowInWebAccess;
};


