
[ClassVersion("1.0.0.0"), FriendlyName("xRDSessionCollectionConfiguration")]
class MSFT_xRDSessionCollectionConfiguration : OMI_BaseResource
{
    [key, Description("Specifies the name of a session collection. ")] string CollectionName;
    [write, Description("Specifies the maximum time, in minutes, an active session runs. After this period, the RD Session Host server ends the session. ")] uint32 ActiveSessionLimitMin;
    [write, Description("Indicates whether to use Network Level Authentication (NLA). If this value is $True, Remote Desktop uses NLA to authenticate a user before the user sees a logon screen. ")] boolean AuthenticateUsingNLA;
    [write, Description("Indicates whether the Remote Desktop client attempts to reconnect after a connection interruption. ")] boolean AutomaticReconnectionEnabled;
    [write, Description("Specifies an action for an RD Session Host server to take after a connection interruption. The acceptable values for this parameter are: None, Disconnect, LogOff.")] string BrokenConnectionAction;
    [write, Description("Specifies a type of client device to be redirected to an RD Session Host server in this session collection. The acceptable values for this parameter are: None, AudioVideoPlayBack, AudioRecording, COMPort, PlugAndPlayDevice, SmartCard, Clipboard, LPTPort, Drive, TimeZone.  You can use binary-or to combine two or more values of this enum to specify multiple client device types.")] string ClientDeviceRedirectionOptions;
    [write, Description("Indicates whether to use the client printer or server printer as the default printer. If this value is $True, use the client printer as default. If this value is $False, use the server as default.")] boolean ClientPrinterAsDefault;
    [write, Description("Indicates whether to use client printer redirection, which routes print jobs from the Remote Desktop session to a printer attached to the client computer.")] boolean ClientPrinterRedirected;
    [write, Description("Specifies a description of the session collection. ")] string CollectionDescription;
    [write, Description("Specifies the Remote Desktop Connection Broker (RD Connection Broker) server for a Remote Desktop deployment.")] string ConnectionBroker;
    [write, Description("Specifies Remote Desktop Protocol (RDP) settings to include in the .rdp files for all Windows Server 2012 RemoteApp programs and remote desktops published in this collection. ")] string CustomRdpProperty;
    [write, Description("Specifies a length of time, in minutes. After client disconnection from a session for this period, the RD Session Host ends the session.")] uint32 DisconnectedSessionLimitMin;
    [write, Description("Specifies the level of data encryption used for a Remote Desktop session. The acceptable values for this parameter are: Low, ClientCompatible, High, FipsCompliant. The default value is ClientCompatible.")] string EncryptionLevel;
    [write, Description("Specifies the length of time, in minutes, to wait before an RD Session Host logs off or disconnects an idle session. The BrokenConnectionAction parameter determines whether to log off or disconnect. ")] uint32 IdleSessionLimitMin;
    [write, Description("Specifies the maximum number of client monitors that an RD Session Host server can redirect to a remote session. The highest value for this parameter is 16.")] uint32 MaxRedirectedMonitors;
    [write, Description("Specifies whether to enable the Remote Desktop Easy Print driver.")] boolean RDEasyPrintDriverEnabled;
    [write, Description("Specifies which security protocol to use. The acceptable values for this parameter are:  RDP, Negotiate, SSL.  The default value is Negotiate.")] string SecurityLayer;
    [write, Description("Specifies whether to delete temporary folders from the RD Session Host server for a disconnected session. ")] boolean TemporaryFoldersDeletedOnExit;
    [write, Description("Specifies a domain group authorized to connect to the RD Session Host servers in a session collection. ")] string UserGroup;
};









